USE [master]
GO

/****** Object:  Database [STRAES_XM]    Script Date: 13/03/2020 11:18:06 ******/
CREATE DATABASE [STRAES_XM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STRAES_XM', FILENAME = N'D:\Arquivos de Programas\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\STRAES_XM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'STRAES_XM_log', FILENAME = N'D:\Arquivos de Programas\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\STRAES_XM_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STRAES_XM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [STRAES_XM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [STRAES_XM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [STRAES_XM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [STRAES_XM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [STRAES_XM] SET ARITHABORT OFF 
GO

ALTER DATABASE [STRAES_XM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [STRAES_XM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [STRAES_XM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [STRAES_XM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [STRAES_XM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [STRAES_XM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [STRAES_XM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [STRAES_XM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [STRAES_XM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [STRAES_XM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [STRAES_XM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [STRAES_XM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [STRAES_XM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [STRAES_XM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [STRAES_XM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [STRAES_XM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [STRAES_XM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [STRAES_XM] SET RECOVERY FULL 
GO

ALTER DATABASE [STRAES_XM] SET  MULTI_USER 
GO

ALTER DATABASE [STRAES_XM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [STRAES_XM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [STRAES_XM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [STRAES_XM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [STRAES_XM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [STRAES_XM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [STRAES_XM] SET  READ_WRITE 
GO

USE [STRAES_XM]
GO

CREATE SCHEMA [cfg]
AUTHORIZATION dbo
GO

CREATE SCHEMA [sis]
AUTHORIZATION dbo
GO

CREATE SCHEMA [log]
AUTHORIZATION dbo
GO

CREATE SCHEMA [old]
AUTHORIZATION dbo
GO