--select * from cfg.MODULO /*41, 42*/

INSERT INTO CFG.MODULO ( ID_MODULO_PAI, DESCRICAO, COMPONENTE, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES ( NULL, 'Área Principal - Correção de Duplicidade', 'BtnMnuCorrigeDuplicidade', 1, 'admin', GETDATE() )

INSERT INTO CFG.MODULO ( ID_MODULO_PAI, DESCRICAO, COMPONENTE, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES ( 26, 'Menu Parâmetros - Correção de Duplicidade', 'mnuCorDup', 1, 'admin', GETDATE() )

--SELECT * FROM CFG.USUARIO /*1, 4, 5*/
--SELECT * FROM CFG.USUARIO_MODULO

/*COM PERMISSÃO*/

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (1, 41, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (1, 42, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (4, 41, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (4, 42, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (5, 41, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (5, 42, 1, 0, 'admin', GETDATE() )

/*SEM PERMISSÃO*/

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (2, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (2, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (6, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (6, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (7, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (7, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (8, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (8, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (9, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (9, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (10, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (10, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (11, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (11, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (12, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (12, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (15, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (15, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (16, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (16, 42, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (17, 41, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (17, 42, 0, 0, 'admin', GETDATE() )
