USE [STRAES_XM]
GO

/****** Object:  View [sis].[V_CORRIGE_DUPLICIDADE]    Script Date: 22/07/2023 18:47:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [sis].[V_CORRIGE_DUPLICIDADE]
AS
SELECT 
	A.MATRICULA,
	A.NOME,
	B.ID_FINANCEIRO,
	B.ANO,
	B.MES,
	B.REFER,
	( SELECT COUNT(REFER) FROM SIS.PESSOA C INNER JOIN SIS.FINANCEIRO D ON ( C.ID_PESSOA = D.ID_PESSOA ) WHERE C.MATRICULA = A.MATRICULA AND D.REFER = B.REFER ) AS QUANTIDADE,
	B.DT_VENCIMENTO,
	B.DT_PAGAMENTO,
	E.DESCRICAO AS FORMA_PAGAMENTO
FROM SIS.PESSOA A
INNER JOIN SIS.FINANCEIRO B
	ON ( A.ID_PESSOA = B.ID_PESSOA )
LEFT JOIN SIS.FORMA_PAGAMENTO E
	ON ( B.ID_FORMA_PAGAMENTO = E.ID_FORMA_PAGAMENTO )

GO


