USE [STRAES_XM]
GO

/****** Object:  StoredProcedure [cfg].[P_CONFIGURACAO_DELETE]    Script Date: 22/07/2023 19:11:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [sis].[P_FINANCEIRO_DELETE] (
	@ID_FINANCEIRO		INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	DECLARE @ID_FINANCEIRO_ESTORNO		INT
	DECLARE @ID_FINANCEIRO_ALTERACAO	INT

	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN

		/*FINANCEIRO_ESTORNO*/
		SET @ID_FINANCEIRO_ESTORNO = (SELECT COUNT(ID_FINANCEIRO_ESTORNO) FROM [sis].[FINANCEIRO_ESTORNO] WHERE ID_FINANCEIRO =@ID_FINANCEIRO)

		IF @ID_FINANCEIRO_ESTORNO > 0
			BEGIN
				INSERT INTO [log].[FINANCEIRO_ESTORNO] ([ID_FINANCEIRO_ESTORNO], [ID_FINANCEIRO], [OBSERVACAO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
				SELECT ID_FINANCEIRO_ESTORNO, ID_FINANCEIRO, OBSERVACAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[FINANCEIRO_ESTORNO] WHERE ID_FINANCEIRO =@ID_FINANCEIRO

				DELETE FROM [sis].[FINANCEIRO_ESTORNO]
				WHERE ID_FINANCEIRO =@ID_FINANCEIRO
			END

		/*FINANCEIRO_ALTERACAO*/
		SET @ID_FINANCEIRO_ALTERACAO = (SELECT COUNT(ID_FINANCEIRO_ALTERACAO) FROM SIS.FINANCEIRO_ALTERACAO WHERE ID_FINANCEIRO = @ID_FINANCEIRO)

		IF @ID_FINANCEIRO_ALTERACAO > 0
			BEGIN
				INSERT INTO [log].[FINANCEIRO_ALTERACAO] ([ID_FINANCEIRO_ALTERACAO], [ID_FINANCEIRO], [DT_VENCIMENTO], [VL_DESCONTO_ORIGINAL], [VL_DESCONTO], [VL_JUROS_ORIGINAL], [VL_JUROS], [OBSERVACAO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
				SELECT ID_FINANCEIRO_ALTERACAO, ID_FINANCEIRO, DT_VENCIMENTO, VL_DESCONTO_ORIGINAL, VL_DESCONTO, VL_JUROS_ORIGINAL, VL_JUROS, OBSERVACAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[FINANCEIRO_ALTERACAO] WHERE ID_FINANCEIRO =@ID_FINANCEIRO

				DELETE FROM [sis].[FINANCEIRO_ALTERACAO]
				WHERE ID_FINANCEIRO =@ID_FINANCEIRO
			END

		/*FINANCEIRO*/
		INSERT INTO [log].[FINANCEIRO] ([ID_FINANCEIRO], [ID_PESSOA], [MES], [ANO], [REFER], [DT_VENCIMENTO], [VL_REFER], [VL_DESCONTO], [DT_PAGAMENTO], [VL_PAGO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
		SELECT ID_FINANCEIRO, ID_PESSOA, MES, ANO, REFER, DT_VENCIMENTO, VL_REFER, VL_DESCONTO, DT_PAGAMENTO, VL_PAGO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[FINANCEIRO] WHERE ID_FINANCEIRO =@ID_FINANCEIRO

		DELETE FROM [sis].[FINANCEIRO]
		WHERE ID_FINANCEIRO =@ID_FINANCEIRO

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


