USE STRAES_XM

DECLARE @CONTADOR INT,	
	    @QUANTIDADE INT,
		@ID_FINANCEIRO INT,		    
		@DATA_VENCIMENTO SMALLDATETIME

SET @CONTADOR = (SELECT COUNT(*) FROM SIS.FINANCEIRO (NOLOCK) WHERE ID_FORMA_PAGAMENTO IS NULL AND MONTH(DT_VENCIMENTO) = MES)
SET @QUANTIDADE = 1;

WHILE @QUANTIDADE <= @CONTADOR
BEGIN
	SET @ID_FINANCEIRO = (SELECT TOP 1 ID_FINANCEIRO FROM SIS.FINANCEIRO (NOLOCK) WHERE ID_FORMA_PAGAMENTO IS NULL AND MONTH(DT_VENCIMENTO) = MES ORDER BY ID_PESSOA, ANO, MES)
	SET @DATA_VENCIMENTO = (SELECT TOP 1 DATEADD(MONTH, 1, DT_VENCIMENTO) FROM SIS.FINANCEIRO (NOLOCK) WHERE ID_FORMA_PAGAMENTO IS NULL AND MONTH(DT_VENCIMENTO) = MES ORDER BY ID_PESSOA, ANO, MES)	

	--PRINT @ID_FINANCEIRO;
	
	UPDATE SIS.FINANCEIRO SET
		DT_VENCIMENTO =@DATA_VENCIMENTO
	WHERE ID_FINANCEIRO =@ID_FINANCEIRO	

	SET @QUANTIDADE = @QUANTIDADE + 1;

	PRINT CAST(@QUANTIDADE AS VARCHAR(100)) + ' DE ' + CAST(@CONTADOR AS VARCHAR(100))
END