USE [STRAES_XM]
GO

ALTER TABLE [sis].[PESSOA]
ADD DIGINA VARCHAR(100) NULL,
	ID_PADRINHO	INT NULL,
	PADRINHO_ORUNKO VARCHAR(100) NULL;

ALTER TABLE [sis].[PESSOA]  WITH CHECK 
ADD CONSTRAINT [PADRINHO_PESSOA] FOREIGN KEY([ID_PADRINHO])
REFERENCES [sis].[PESSOA] ([ID_PESSOA]);

ALTER TABLE [log].[PESSOA]
ADD DIGINA VARCHAR(100) NULL,
	ID_PADRINHO	INT NULL,
	PADRINHO_ORUNKO VARCHAR(100) NULL;