USE [STRAES_XM]
GO

CREATE TABLE [sis].[ORIXA](
	[ID_ORIXA] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](100) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[USUARIO_OPERACAO] [varchar](20) NOT NULL,
	[DATA_OPERACAO] [smalldatetime] NOT NULL,
 CONSTRAINT [PK_ORIXA] PRIMARY KEY CLUSTERED 
(
	[ID_ORIXA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [sis].[ORIXA] ADD  CONSTRAINT [DEF_ORIXA_ATIVO]  DEFAULT ((1)) FOR [ATIVO]
GO


ALTER TABLE [sis].[ORIXA] ADD  CONSTRAINT [DEF_ORIXA_DATA_OPERACAO]  DEFAULT (getdate()) FOR [DATA_OPERACAO]
GO


CREATE TABLE [log].[ORIXA](
	[ID_ORIXA] [int] NULL,
	[DESCRICAO] [varchar](100) NULL,
	[USUARIO_OPERACAO] [varchar](20) NULL,
	[DATA_OPERACAO] [smalldatetime] NULL,
	[STATUS_OPERACAO][varchar](10) NULL )