USE [STRAES_XM]
GO

DELETE FROM SIS.SANTO

DROP INDEX [sis].[SANTO].[IDX_SANTO_DESCRICAO];

ALTER TABLE [sis].[SANTO]
DROP COLUMN DESCRICAO;

ALTER TABLE [sis].[SANTO]
ADD ID_ORDEM INT NULL,
	ID_ORIXA INT NULL,
	FUNDAMENTO VARCHAR(100) NULL;

ALTER TABLE [sis].[SANTO]  WITH CHECK 
ADD CONSTRAINT [ORDEM_SANTO] FOREIGN KEY([ID_ORDEM])
REFERENCES [sis].[ORDEM] ([ID_ORDEM]);

ALTER TABLE [sis].[SANTO]  WITH CHECK 
ADD CONSTRAINT [ORIXAO_SANTO] FOREIGN KEY([ID_ORIXA])
REFERENCES [sis].[ORIXA] ([ID_ORIXA]);


ALTER TABLE [log].[SANTO]
DROP COLUMN DESCRICAO;

ALTER TABLE [log].[SANTO]
ADD ID_ORDEM INT NULL,
	ID_ORIXA INT NULL,
	FUNDAMENTO VARCHAR(100) NULL;