USE [STRAES_XM]
GO

ALTER VIEW [sis].[V_DADOS_PESSOA]
AS
SELECT
	P.ID_PESSOA,
	P.ID_CLASSIFICACAO,
	C.DESCRICAO AS CLASSIFICACAO,
	P.ID_ATIVIDADE,
	A.DESCRICAO AS ATIVIDADE,
	P.ID_ESTADO_CIVIL,
	EC.DESCRICAO AS ESTADO_CIVIL,
	P.MATRICULA,
	P.NOME,
	P.DT_NASCIMENTO,
	P.PAI,
	P.MAE,
	P.PROFISSAO,
	P.CONJUGE,
	P.RAZAO_SOCIAL,
	P.LOGRADOURO AS [EMPRESA_LOGRADOURO],
	P.NUMERO AS [EMPRESA_NUMERO],
	P.COMPLEMENTO AS [EMPRESA_COMPLEMENTO],
	P.BAIRRO AS [EMPRESA_BAIRRO],
	P.ID_CIDADE,
	CID.NOME AS [EMPRESA_CIDADE],
	EST.ID_ESTADO,
	EST.NOME AS [EMPRESA_ESTADO],
	PAI.ID_PAIS,
	PAI.NOME_PT AS [EMPRESA_PAIS],
	P.CEP AS [EMPRESA_CEP],
	P.DATA_ADMISSAO_TERREIRO,
	P.DIGINA,
	PAD.NOME AS PADRINHO,
	P.PADRINHO_ORUNKO,
	P.ATIVO,
	( SELECT CASE WHEN COUNT(*) > 0 THEN 'Inadimplente' WHEN COUNT(*) = 0 THEN 'Adimplente' END AS STATUS FROM [sis].[FINANCEIRO] WHERE DT_PAGAMENTO IS NULL AND DT_VENCIMENTO < GETDATE() AND ID_PESSOA = P.ID_PESSOA ) AS STATUS
FROM [sis].[PESSOA] P

LEFT JOIN [sis].[CLASSIFICACAO] C
	ON ( P.ID_CLASSIFICACAO = C.ID_CLASSIFICACAO )

LEFT JOIN [sis].[ATIVIDADE] A
	ON ( P.ID_ATIVIDADE = A.ID_ATIVIDADE )

LEFT JOIN [cfg].[ESTADO_CIVIL] EC
	ON ( P.ID_ESTADO_CIVIL = EC.ID_ESTADO_CIVIL )

LEFT JOIN [cfg].[CIDADE] CID
	ON ( P.ID_CIDADE = CID.ID_CIDADE )

LEFT JOIN [cfg].[ESTADO] EST
	ON ( CID.ID_ESTADO = EST.ID_ESTADO )

LEFT JOIN [cfg].[PAIS] PAI
	ON ( EST.ID_PAIS = PAI.ID_PAIS )

LEFT JOIN [sis].[PESSOA] PAD
	ON ( P.ID_PADRINHO = PAD.ID_PESSOA )
GO


