USE [STRAES_XM]
GO

/****** Object:  View [sis].[V_DADOS_PESSOA_SANTO]    Script Date: 19/08/2023 02:23:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [sis].[V_DADOS_PESSOA_SANTO]
AS
SELECT 
	P.ID_PESSOA,
	S.ID_SANTO,
	ORD.ID_ORDEM,
	ORD.DESCRICAO AS ORDEM,
	ORI.ID_ORIXA,
	ORI.DESCRICAO AS ORIXA,
	S.FUNDAMENTO,
	S.USUARIO_OPERACAO,
	S.DATA_OPERACAO
FROM [sis].[PESSOA] P
LEFT JOIN [sis].[SANTO] S
	ON ( P.ID_PESSOA = S.ID_PESSOA )
LEFT JOIN [sis].[ORDEM] ORD
	ON ( S.ID_ORDEM = ORD.ID_ORDEM )
LEFT JOIN [sis].[ORIXA] ORI
	ON ( S.ID_ORIXA = ORI.ID_ORIXA )
GO


