USE [STRAES_XM]
GO

/****** Object:  StoredProcedure [sis].[P_PESSOA_INSERT]    Script Date: 19/08/2023 02:27:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [sis].[P_PESSOA_INSERT] (
	@MATRICULA					VARCHAR(10),
	@ID_CLASSIFICACAO			INT,
	@NOME						VARCHAR(100),
	@DT_NASCIMENTO				SMALLDATETIME,
	@ID_ATIVIDADE				INT,
	@ID_PLANO					INT,
	@PLANO_REFER_INICIO			CHAR(6),
	@PLANO_REFER_FIM			CHAR(6),
	@ID_FILANTROPIA				INT,
	@FILANTROPIA_REFER_INICIO	CHAR(6),
	@FILANTROPIA_REFER_FIM		CHAR(6),
	@ID_ESTADO_CIVIL			INTEGER,
	@ID_CIDADE					INTEGER,
	@PAI						VARCHAR(100),
	@MAE						VARCHAR(100),
	@PROFISSAO					VARCHAR(100),
	@CONJUGE					VARCHAR(100),
	@RAZAO_SOCIAL				VARCHAR(100),
	@LOGRADOURO					VARCHAR(40),
	@NUMERO						VARCHAR(10),
	@COMPLEMENTO				VARCHAR(20),
	@BAIRRO						VARCHAR(50),
	@CEP						VARCHAR(8),
	@DATA_ADMISSAO_TERREIRO		SMALLDATETIME,
	@DIGINA						VARCHAR(100),
	@ID_PADRINHO				INT,
	@PADRINHO_ORUNKO			VARCHAR(100),
	@USUARIO_OPERACAO			VARCHAR(20) )
AS
BEGIN
	DECLARE @ID_PESSOA		INT,
			@COUNT			INT,
			@QTDE			INT,
			@DIA			CHAR(2),
			@MES			CHAR(2),
			@ANO			CHAR(4),
			@QTDE_FIM		INT,
			@REFER			CHAR(6),
			@VENCIMENTO		SMALLDATETIME,
			@VALOR			SMALLMONEY,
			@REFER_DESCONTO	CHAR(6),
			@VL_DESCONTO	SMALLMONEY

	SET NOCOUNT ON;

	BEGIN TRY
		-- PESSOA --
		BEGIN TRAN
			INSERT INTO [sis].[PESSOA] ( ID_CLASSIFICACAO, ID_ATIVIDADE, ID_ESTADO_CIVIL, ID_CIDADE, MATRICULA, NOME, DT_NASCIMENTO, ATIVO, PAI, MAE, PROFISSAO, CONJUGE, 
			                             RAZAO_SOCIAL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, DATA_ADMISSAO_TERREIRO, DIGINA, ID_PADRINHO, PADRINHO_ORUNKO, USUARIO_OPERACAO, DATA_OPERACAO )
			VALUES ( @ID_CLASSIFICACAO, @ID_ATIVIDADE, @ID_ESTADO_CIVIL, @ID_CIDADE, @MATRICULA, @NOME, @DT_NASCIMENTO, 1, @PAI, @MAE, @PROFISSAO, @CONJUGE, 
			         @RAZAO_SOCIAL, @LOGRADOURO, @NUMERO, @COMPLEMENTO, @BAIRRO, @CEP, @DATA_ADMISSAO_TERREIRO, @DIGINA, @ID_PADRINHO, @PADRINHO_ORUNKO, @USUARIO_OPERACAO, GETDATE() )

			SET @COUNT = ( SELECT COUNT(ID_PESSOA) FROM [sis].[PESSOA] WHERE NOME =@NOME )

			IF @COUNT = 0
				SET @ID_PESSOA = ( SELECT ( MAX(ID_PESSOA) + 1 ) FROM [sis].[PESSOA] )
			ELSE
				SET @ID_PESSOA = ( SELECT ID_PESSOA FROM [sis].[PESSOA] WHERE NOME =@NOME )
		COMMIT TRAN

		-- PLANO --
		BEGIN TRAN
			IF @ID_PLANO > 0
				BEGIN
					INSERT INTO [sis].[PESSOA_PLANO] ( ID_PESSOA, ID_PLANO, REFER_INICIO, REFER_FIM, USUARIO_OPERACAO, DATA_OPERACAO)
					VALUES ( @ID_PESSOA, @ID_PLANO, @PLANO_REFER_INICIO, @PLANO_REFER_FIM, @USUARIO_OPERACAO, GETDATE())
				END
		COMMIT TRAN

		-- FILANTROPIA --
		BEGIN TRAN
			IF @ID_FILANTROPIA > 0
				BEGIN
					INSERT INTO [sis].[PESSOA_FILANTROPIA] ( ID_PESSOA, ID_FILANTROPIA, REFER_INICIO, REFER_FIM, USUARIO_OPERACAO, DATA_OPERACAO)
					VALUES ( @ID_PESSOA, @ID_FILANTROPIA, @FILANTROPIA_REFER_INICIO, @FILANTROPIA_REFER_FIM, @USUARIO_OPERACAO, GETDATE())
				END
		COMMIT TRAN

		-- FINANCEIRO --
		BEGIN TRAN
			SET @QTDE	  = CAST( SUBSTRING( @PLANO_REFER_INICIO, 1, 2 ) AS INT )
			SET @ANO	  = SUBSTRING( @PLANO_REFER_INICIO, 3, 4 )
			SET @VALOR	  = ( SELECT VALOR FROM [sis].[PLANO] WHERE ID_PLANO =@ID_PLANO )
			SET @QTDE_FIM = CAST( SUBSTRING( @PLANO_REFER_FIM, 1, 2 ) AS INT )

			WHILE @QTDE <= @QTDE_FIM
				BEGIN
					SET @MES		 = REPLICATE( '0', 2 - LEN( CAST( @QTDE AS VARCHAR(2) ) ) ) + CAST( @QTDE AS VARCHAR(2) )
					SET @DIA		 = ( SELECT COALESCE( REPLICATE( '0', 2 - LEN( FIN_DIA_VENCIMENTO ) ) + FIN_DIA_VENCIMENTO, '10' ) FROM [cfg].[CONFIGURACAO] WHERE ATIVO = 1 )
					SET @REFER		 = @MES + @ANO
					SET @VENCIMENTO  = DATEADD(MONTH, 1, CAST((@ANO + '-' + @DIA + '-' + @MES) AS SMALLDATETIME))
					SET @VL_DESCONTO = 0

					IF @ID_FILANTROPIA > 0
						BEGIN
							SET @REFER_DESCONTO = @FILANTROPIA_REFER_INICIO

							WHILE CAST(@REFER_DESCONTO AS INT) <= CAST(@FILANTROPIA_REFER_FIM AS INT)
								BEGIN
									IF @REFER = @REFER_DESCONTO
										SET @VL_DESCONTO = COALESCE( ( SELECT CASE
																		         WHEN VALOR > 0 THEN VALOR
																				 WHEN PERCENTUAL > 0 THEN ( @VALOR * PERCENTUAL ) / 100
																			  ELSE 0 END
															           FROM [sis].[FILANTROPIA]
															           WHERE ID_FILANTROPIA =@ID_FILANTROPIA ), 0 )

									SET @REFER_DESCONTO = REPLICATE('0', 6 - LEN((CAST(@REFER_DESCONTO AS INT) + 10000))) + CAST((CAST(@REFER_DESCONTO AS INT) + 10000) AS CHAR(6))
								END
						END

					EXEC [sis].[P_FINANCEIRO_INSERT] @ID_PESSOA, @REFER, @VENCIMENTO, @VALOR, @VL_DESCONTO, NULL, NULL, @USUARIO_OPERACAO

					SET @QTDE = @QTDE + 1
				END
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


