INSERT INTO [sis].[PESSOA] ( ID_CLASSIFICACAO, MATRICULA, NOME, DT_NASCIMENTO, USUARIO_OPERACAO )
SELECT DISTINCT 
	1 AS ID_CLASSIFICACAO, 
	CONTATO_MATRICULA_MASCARA AS MATRICULA, 
	UPPER(LTRIM(RTRIM(CONTATO_NOMECOMPLETO))) AS NOME, 
	CONTATO_DT_NASCIMENTO AS DT_NASCIMENTO,
	'Importação' AS USUARIO_OPERACAO
FROM [old].[V_DADOS_MENSALIDADE_ANTIGOS] DA
WHERE MENSALIDADE_MESREF <> 0
AND MENSALIDADE_ANO <> 0
ORDER BY 2

SELECT * FROM SIS.PESSOA

/*SELECT DISTINCT
	'EXEC PESSOA_INSERT ',
	CONTATO_MATRICULA_MASCARA, 
	1,
	CONTATO_NOMECOMPLETO,
	CONTATO_DT_NASCIMENTO,
	1,
	1,
	(SELECT MIN(MENSALIDADE_REFER_MASCARA) FROM [old].[V_DADOS_ANTIGOS] WHERE UPPER(LTRIM(RTRIM(CONTATO_NOMECOMPLETO))) = UPPER(DA.CONTATO_NOMECOMPLETO) AND MENSALIDADE_MESREF <> 0 AND MENSALIDADE_ANO <> 0 GROUP BY CONTATO_NOMECOMPLETO) AS REFER_INICIO,
	(SELECT MAX(MENSALIDADE_REFER_MASCARA) FROM [old].[V_DADOS_ANTIGOS] WHERE UPPER(LTRIM(RTRIM(CONTATO_NOMECOMPLETO))) = UPPER(DA.CONTATO_NOMECOMPLETO) AND MENSALIDADE_MESREF <> 0 AND MENSALIDADE_ANO <> 0 GROUP BY CONTATO_NOMECOMPLETO) AS REFER_FIM,
	1,
	(SELECT MIN(MENSALIDADE_REFER_MASCARA) FROM [old].[V_DADOS_ANTIGOS] WHERE UPPER(LTRIM(RTRIM(CONTATO_NOMECOMPLETO))) = UPPER(DA.CONTATO_NOMECOMPLETO) AND MENSALIDADE_MESREF <> 0 AND MENSALIDADE_ANO <> 0 GROUP BY CONTATO_NOMECOMPLETO) AS FILANTROPIA_INICIO,
	(SELECT MAX(MENSALIDADE_REFER_MASCARA) FROM [old].[V_DADOS_ANTIGOS] WHERE UPPER(LTRIM(RTRIM(CONTATO_NOMECOMPLETO))) = UPPER(DA.CONTATO_NOMECOMPLETO) AND MENSALIDADE_MESREF <> 0 AND MENSALIDADE_ANO <> 0 GROUP BY CONTATO_NOMECOMPLETO) AS FILANTROPIA_FIM,
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	'Importação'
FROM [old].[V_DADOS_ANTIGOS] DA
WHERE MENSALIDADE_MESREF <> 0
AND MENSALIDADE_ANO <> 0*/