USE [STRAES_XM]
GO

/****** Object:  StoredProcedure [sis].[P_SANTO_INSERT]    Script Date: 19/08/2023 02:34:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [sis].[P_SANTO_INSERT] (
	@ID_PESSOA			INT,
	@ID_ORDEM			INT,
	@ID_ORIXA			INT,
	@FUNDAMENTO			VARCHAR(100),
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN

			INSERT INTO [sis].[SANTO] ( ID_PESSOA, ID_ORDEM, ID_ORIXA, FUNDAMENTO, USUARIO_OPERACAO, DATA_OPERACAO )
			VALUES ( @ID_PESSOA, @ID_ORDEM, @ID_ORIXA, @FUNDAMENTO, @USUARIO_OPERACAO, GETDATE() )

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


