WITH IMPORTACAO ( ID_PESSOA, REFER, DT_VENCIMENTO, VL_REFER, ID_FORMA_PAGAMENTO, DT_PAGAMENTO, VL_PAGO, USUARIO_OPERACAO )
AS (
		SELECT DISTINCT
			(SELECT ID_PESSOA FROM SIS.PESSOA WHERE NOME = UPPER(LTRIM(RTRIM(DA.CONTATO_NOMECOMPLETO)))) AS [ID_PESSOA],
			MENSALIDADE_REFER_MASCARA AS REFER,
			(SUBSTRING(MENSALIDADE_REFER_MASCARA, 3, 4) + '-' + SUBSTRING(MENSALIDADE_REFER_MASCARA, 1, 2) + '-' + '01') AS DT_VENCIMENTO,	
			PAGAMENTO_VALOR AS VL_REFER,
			(SELECT COALESCE(ID_FORMA_PAGAMENTO, NULL) FROM SIS.FORMA_PAGAMENTO WHERE DESCRICAO = DA.PAGAMENTO_FORMAPAGAMENTO AND PAGAMENTO_FORMAPAGAMENTO <> '0') AS ID_FORMA_PAGAMENTO,
			PAGAMENTO_DATAPAGAMENTO AS DT_PAGAMENTO,
			PAGAMENTO_VALOR AS VL_PAGO,
			'importação' AS USUARIO_OPERACAO
		FROM [old].[V_DADOS_MENSALIDADE_ANTIGOS] DA
		WHERE MENSALIDADE_MESREF <> 0
		AND MENSALIDADE_ANO <> 0
)

INSERT INTO [sis].[FINANCEIRO] ( ID_PESSOA, REFER, DT_VENCIMENTO, VL_REFER, ID_FORMA_PAGAMENTO, DT_PAGAMENTO, VL_PAGO, USUARIO_OPERACAO )
SELECT ID_PESSOA, REFER, DT_VENCIMENTO, COALESCE (VL_REFER, 0) AS VL_REFER, ID_FORMA_PAGAMENTO, DT_PAGAMENTO, VL_PAGO, USUARIO_OPERACAO FROM IMPORTACAO
WHERE ID_PESSOA IS NOT NULL