USE [STRAES_XM]
GO

/****** Object:  StoredProcedure [sis].[P_SANTO_DELETE]    Script Date: 19/08/2023 02:34:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [sis].[P_SANTO_DELETE] (
	@ID_PESSOA			INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN

			INSERT INTO [log].[SANTO] ( ID_SANTO, ID_PESSOA, ID_ORDEM, ID_ORIXA, FUNDAMENTO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO )
			SELECT ID_SANTO, @ID_PESSOA, ID_ORDEM, ID_ORIXA, FUNDAMENTO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[SANTO] WHERE ID_PESSOA =@ID_PESSOA

			DELETE FROM [sis].[SANTO]
			WHERE ID_PESSOA =@ID_PESSOA

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


