INSERT [sis].[PAGAMENTO_DIVERSO] ( ID_FORMA_PAGAMENTO, DATA_PAGAMENTO, VALOR, DESCRICAO, USUARIO_OPERACAO )
SELECT 	
	CASE 
		WHEN (SELECT CASE WHEN ID_FORMA_PAGAMENTO IS NULL THEN 1 ELSE ID_FORMA_PAGAMENTO END FROM SIS.FORMA_PAGAMENTO WHERE DESCRICAO = DA.PAGAMENTO_FORMAPAGAMENTO AND PAGAMENTO_FORMAPAGAMENTO <> '0') IS NULL THEN 1
	ELSE (SELECT CASE WHEN ID_FORMA_PAGAMENTO IS NULL THEN 1 ELSE ID_FORMA_PAGAMENTO END FROM SIS.FORMA_PAGAMENTO WHERE DESCRICAO = DA.PAGAMENTO_FORMAPAGAMENTO AND PAGAMENTO_FORMAPAGAMENTO <> '0')		
	END AS ID_FORMA_PAGAMENTO,
	PAGAMENTO_DATAPAGAMENTO AS DATA_PAGAMENTO,
	PAGAMENTO_VALOR AS VALOR,
	LTRIM(RTRIM(PAGAMENTO_OBSERVACAO)) AS DESCRICAO,
	'importação' AS USUARIO_OPERACAO
FROM [old].[V_DADOS_PAGAMENTOS_ANTIGOS] DA