USE [STRAES_XM]
GO

CREATE PROCEDURE [sis].[P_ORDEM_DELETE] (
	@ID_ORDEM			INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
		
			INSERT INTO [log].[ORDEM] ( ID_ORDEM, DESCRICAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO )
			SELECT @ID_ORDEM, DESCRICAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[ORDEM] WHERE ID_ORDEM =@ID_ORDEM

			DELETE FROM [sis].[ORDEM]
			WHERE ID_ORDEM =@ID_ORDEM

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


