USE [STRAES_XM]
GO

CREATE PROCEDURE [sis].[P_ORIXA_INSERT] (
	@DESCRICAO			VARCHAR(100),
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN

			INSERT INTO [sis].[ORIXA] ( DESCRICAO, USUARIO_OPERACAO, DATA_OPERACAO )
			VALUES ( @DESCRICAO, @USUARIO_OPERACAO, GETDATE() )

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


