USE [STRAES_XM]
GO

CREATE PROCEDURE [sis].[P_ORIXA_DELETE] (
	@ID_ORIXA			INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
		
			INSERT INTO [log].[ORIXA] ( ID_ORIXA, DESCRICAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO )
			SELECT @ID_ORIXA, DESCRICAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [sis].[ORIXA] WHERE ID_ORIXA =@ID_ORIXA

			DELETE FROM [sis].[ORIXA]
			WHERE ID_ORIXA =@ID_ORIXA

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


