USE [STRAES_XM]
GO

/****** Object:  Trigger [sis].[T_PESSOA_INSERT]    Script Date: 19/08/2023 02:47:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER TRIGGER [sis].[T_PESSOA_INSERT]
   ON  [sis].[PESSOA]
   AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
			INSERT INTO [log].[PESSOA] ( ID_PESSOA, ID_CLASSIFICACAO, ID_ATIVIDADE, ID_ESTADO_CIVIL, ID_CIDADE, MATRICULA, NOME, DT_NASCIMENTO, ATIVO, PAI, MAE, PROFISSAO, CONJUGE, 
			                             RAZAO_SOCIAL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, DATA_ADMISSAO_TERREIRO, DIGINA, ID_PADRINHO, PADRINHO_ORUNKO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO  )
			SELECT ID_PESSOA, ID_CLASSIFICACAO, ID_ATIVIDADE, ID_ESTADO_CIVIL, ID_CIDADE, MATRICULA, NOME, DT_NASCIMENTO, ATIVO, PAI, MAE, PROFISSAO, CONJUGE, 
                   RAZAO_SOCIAL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, DATA_ADMISSAO_TERREIRO, DIGINA, ID_PADRINHO, PADRINHO_ORUNKO, USUARIO_OPERACAO, GETDATE(), 'INSERT' FROM INSERTED 
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


