USE [STRAES_XM]
GO

/****** Object:  Trigger [sis].[T_SANTO_INSERT]    Script Date: 19/08/2023 02:49:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER TRIGGER [sis].[T_SANTO_INSERT]
   ON  [sis].[SANTO]
   AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
			INSERT INTO [log].[SANTO] ( ID_SANTO, ID_PESSOA, ID_ORDEM, ID_ORIXA, FUNDAMENTO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO )
			SELECT ID_SANTO, ID_PESSOA, ID_ORDEM, ID_ORIXA, FUNDAMENTO, USUARIO_OPERACAO, GETDATE(), 'INSERT' FROM INSERTED
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


