USE [STRAES_XM]
GO

CREATE TRIGGER [sis].[T_ORDEM_INSERT]
   ON  [sis].[ORDEM]
   AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
			INSERT INTO [log].[ORDEM] ( ID_ORDEM, DESCRICAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO )
			SELECT ID_ORDEM, DESCRICAO, USUARIO_OPERACAO, GETDATE(), 'INSERT' FROM INSERTED
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


