INSERT INTO CFG.MODULO ( ID_MODULO_PAI, DESCRICAO, COMPONENTE, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES ( 13, 'Menu Cadastro - Ordem', 'mnuCadOrd', 1, 'admin', GETDATE() )

INSERT INTO CFG.MODULO ( ID_MODULO_PAI, DESCRICAO, COMPONENTE, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES ( 13, 'Menu Cadastro - Orixás', 'mnuCadOri', 1, 'admin', GETDATE() )

/*COM PERMISSÃO*/

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (1, 43, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (1, 44, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (4, 43, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (4, 44, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (5, 43, 1, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (5, 44, 1, 0, 'admin', GETDATE() )

/*SEM PERMISSÃO*/

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (2, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (2, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (6, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (6, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (7, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (7, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (8, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (8, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (9, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (9, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (10, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (10, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (11, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (11, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (12, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (12, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (15, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (15, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (16, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (16, 44, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (17, 43, 0, 0, 'admin', GETDATE() )

INSERT INTO CFG.USUARIO_MODULO ( ID_USUARIO, ID_MODULO, PERMISSAO, BLOQUEADO, USUARIO_OPERACAO, DATA_OPERACAO )
VALUES (17, 44, 0, 0, 'admin', GETDATE() )
