USE [STRAES_XM]
GO

CREATE PROCEDURE [sis].[P_ORDEM_DESATIVAR] (
	@ID_ORDEM	INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN
			UPDATE [sis].[ORDEM] SET
				[ATIVO]				= 0,
				[USUARIO_OPERACAO]	= @USUARIO_OPERACAO,
				[DATA_OPERACAO]		= GETDATE()
			WHERE ID_ORDEM = @ID_ORDEM
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


