USE [STRAES_XM]
GO

/****** Object:  StoredProcedure [sis].[P_TIPO_CONTATO_UPDATE]    Script Date: 20/08/2023 01:27:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [sis].[P_ORDEM_UPDATE] (
	@ID_ORDEM	INT,
	@DESCRICAO			VARCHAR(100),
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN

		UPDATE [sis].[ORDEM] SET
			DESCRICAO		 =@DESCRICAO,
			USUARIO_OPERACAO =@USUARIO_OPERACAO,
			DATA_OPERACAO 	 = GETDATE()
		WHERE ID_ORDEM =@ID_ORDEM

		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO


