--ALTERAÇÕES 

--CRIAÇÃO DA PROCEDURE [sis].[P_PESSOA_DELETE]
CREATE PROCEDURE [sis].[P_PESSOA_DELETE] (
	@ID_PESSOA			INT,
	@USUARIO_OPERACAO	VARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		BEGIN TRAN			
			---------- [SIS].[CONTATO] ----------
			INSERT INTO [LOG].[CONTATO] ([ID_CONTATO], [ID_PESSOA], [ID_TIPO_CONTATO], [DESCRICAO], [ATIVO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
			SELECT ID_CONTATO, ID_PESSOA, ID_TIPO_CONTATO, DESCRICAO, ATIVO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[CONTATO] WHERE ID_CONTATO IN (SELECT ID_CONTATO FROM [SIS].[CONTATO] WHERE ID_PESSOA = @ID_PESSOA)
						
			DELETE FROM [SIS].[CONTATO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[SANTO] ----------
			INSERT INTO [LOG].[SANTO] (ID_SANTO, ID_PESSOA, DESCRICAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_SANTO, ID_PESSOA, DESCRICAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[SANTO] WHERE ID_SANTO IN (SELECT ID_SANTO FROM [SIS].[SANTO] WHERE ID_PESSOA = @ID_PESSOA)
					   			 		  		  		 	   		
			DELETE FROM [SIS].[SANTO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[OBRIGACAO] ----------
			INSERT INTO [LOG].[OBRIGACAO] ([ID_OBRIGACAO], [ID_PESSOA], [DATA], [DESCRICAO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
			SELECT ID_OBRIGACAO, ID_PESSOA, DATA, DESCRICAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[OBRIGACAO] WHERE ID_OBRIGACAO IN (SELECT ID_OBRIGACAO FROM [SIS].[OBRIGACAO] WHERE ID_PESSOA = @ID_PESSOA)
			
			DELETE FROM [SIS].[OBRIGACAO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[PESSOA_PLANO] ----------
			INSERT INTO [LOG].[PESSOA_PLANO] (ID_PESSOA_PLANO, ID_PESSOA, ID_PLANO, REFER_INICIO, REFER_FIM, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_PESSOA_PLANO, ID_PESSOA, ID_PLANO, REFER_INICIO, REFER_FIM, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[PESSOA_PLANO] WHERE ID_PESSOA_PLANO IN (SELECT ID_PESSOA_PLANO FROM [SIS].[PESSOA_PLANO] WHERE ID_PESSOA = @ID_PESSOA)

			DELETE FROM [SIS].[PESSOA_PLANO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[PESSOA_FILANTROPIA] ----------
			INSERT INTO [LOG].[PESSOA_FILANTROPIA] (ID_PESSOA_FILANTROPIA, ID_PESSOA, ID_FILANTROPIA, REFER_INICIO, REFER_FIM, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_PESSOA_FILANTROPIA, ID_PESSOA, ID_FILANTROPIA, REFER_INICIO, REFER_FIM, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[PESSOA_FILANTROPIA] WHERE ID_PESSOA_FILANTROPIA IN (SELECT ID_PESSOA_FILANTROPIA FROM [SIS].[PESSOA_FILANTROPIA] WHERE ID_PESSOA = @ID_PESSOA)

			DELETE FROM [SIS].[PESSOA_FILANTROPIA] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[MOTIVO_STATUS] ----------
			INSERT INTO [LOG].[MOTIVO_STATUS] (ID_MOTIVO_STATUS, ID_PESSOA, DT_ALTERACAO, MOTIVO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_MOTIVO_STATUS, ID_PESSOA, DT_ALTERACAO, MOTIVO, USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[MOTIVO_STATUS] WHERE ID_MOTIVO_STATUS IN ( SELECT ID_MOTIVO_STATUS FROM [SIS].[MOTIVO_STATUS] WHERE ID_PESSOA = @ID_PESSOA)

			DELETE FROM [SIS].[MOTIVO_STATUS] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[DOCUMENTO] ----------
			INSERT INTO [LOG].[DOCUMENTO] (ID_DOCUMENTO, ID_PESSOA, ID_TIPO_DOCUMENTO, DESCRICAO, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_DOCUMENTO, ID_PESSOA, ID_TIPO_DOCUMENTO, DESCRICAO, ATIVO, USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[DOCUMENTO] WHERE ID_DOCUMENTO IN (SELECT ID_DOCUMENTO FROM [SIS].[DOCUMENTO] WHERE ID_PESSOA =@ID_PESSOA)

			DELETE FROM [SIS].[DOCUMENTO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[ENDERECO] ----------
			INSERT INTO [LOG].[ENDERECO] (ID_ENDERECO, ID_PESSOA, ID_TIPO_ENDERECO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, ATIVO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_ENDERECO, ID_PESSOA, ID_TIPO_ENDERECO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, ATIVO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[ENDERECO] WHERE ID_ENDERECO IN (SELECT ID_ENDERECO FROM [SIS].[ENDERECO] WHERE ID_PESSOA =@ID_PESSOA)
			
			DELETE FROM [SIS].[ENDERECO] WHERE ID_PESSOA IN ( SELECT ID_PESSOA FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA )
			
			---------- [SIS].[FINANCEIRO_ESTORNO] ----------
			INSERT INTO [LOG].[FINANCEIRO_ESTORNO] (ID_FINANCEIRO_ESTORNO, ID_FINANCEIRO, OBSERVACAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_FINANCEIRO_ESTORNO, ID_FINANCEIRO, OBSERVACAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[FINANCEIRO_ESTORNO] WHERE ID_FINANCEIRO_ESTORNO IN (SELECT ID_FINANCEIRO_ESTORNO FROM [SIS].[FINANCEIRO_ESTORNO] WHERE ID_FINANCEIRO IN (SELECT ID_FINANCEIRO FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA =@ID_PESSOA))
			
			DELETE FROM [SIS].[FINANCEIRO_ESTORNO] WHERE ID_FINANCEIRO IN ( SELECT ID_FINANCEIRO FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA = @ID_PESSOA )
			
			---------- [SIS].[FINANCEIRO_ALTERACAO] ----------			
			INSERT INTO [LOG].[FINANCEIRO_ALTERACAO] (ID_FINANCEIRO_ALTERACAO, ID_FINANCEIRO, DT_VENCIMENTO, VL_DESCONTO_ORIGINAL, VL_DESCONTO, VL_JUROS_ORIGINAL, VL_JUROS, OBSERVACAO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_FINANCEIRO_ALTERACAO, ID_FINANCEIRO, DT_VENCIMENTO, VL_DESCONTO_ORIGINAL, VL_DESCONTO, VL_JUROS_ORIGINAL, VL_JUROS, OBSERVACAO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[FINANCEIRO_ALTERACAO] WHERE ID_FINANCEIRO_ALTERACAO IN (SELECT ID_FINANCEIRO_ALTERACAO FROM [SIS].[FINANCEIRO_ALTERACAO] WHERE ID_FINANCEIRO IN (SELECT ID_FINANCEIRO FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA =@ID_PESSOA))

			DELETE FROM [SIS].[FINANCEIRO_ALTERACAO] WHERE ID_FINANCEIRO IN ( SELECT ID_FINANCEIRO FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA = @ID_PESSOA )

			---------- [SIS].[FINANCEIRO] ----------	
			INSERT INTO [LOG].[FINANCEIRO] (ID_FINANCEIRO, ID_PESSOA, MES, ANO, REFER, DT_VENCIMENTO, VL_REFER, VL_DESCONTO, DT_PAGAMENTO, VL_PAGO, USUARIO_OPERACAO, DATA_OPERACAO, STATUS_OPERACAO)
			SELECT ID_FINANCEIRO, ID_PESSOA, MES, ANO, REFER, DT_VENCIMENTO, VL_REFER, VL_DESCONTO, DT_PAGAMENTO, VL_PAGO, @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA = @ID_PESSOA
			
			DELETE FROM [SIS].[FINANCEIRO] WHERE ID_PESSOA = @ID_PESSOA

			---------- [SIS].[PESSOA] ----------
			INSERT INTO [LOG].[PESSOA] ([ID_PESSOA], [ID_CLASSIFICACAO], [ID_ATIVIDADE], [ID_ESTADO_CIVIL], [ID_CIDADE], [MATRICULA], [NOME], [DT_NASCIMENTO], [ATIVO], [PAI], [MAE], [PROFISSAO], [CONJUGE], [RAZAO_SOCIAL], [LOGRADOURO], [NUMERO], [COMPLEMENTO], [BAIRRO], [CEP], [DATA_ADMISSAO_TERREIRO], [USUARIO_OPERACAO], [DATA_OPERACAO], [STATUS_OPERACAO])
			SELECT [ID_PESSOA], [ID_CLASSIFICACAO], [ID_ATIVIDADE], [ID_ESTADO_CIVIL], [ID_CIDADE], [MATRICULA], [NOME], [DT_NASCIMENTO], [ATIVO], [PAI], [MAE], [PROFISSAO], [CONJUGE], [RAZAO_SOCIAL], [LOGRADOURO], [NUMERO], [COMPLEMENTO], [BAIRRO], [CEP], [DATA_ADMISSAO_TERREIRO], @USUARIO_OPERACAO, GETDATE(), 'DELETE' FROM [SIS].[PESSOA] WHERE ID_PESSOA =@ID_PESSOA

			DELETE FROM [SIS].[PESSOA] WHERE ID_PESSOA = @ID_PESSOA
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		SELECT
			ERROR_NUMBER() AS ERRORNUMBER,
			ERROR_SEVERITY() AS ERRORSEVERITY,
			ERROR_STATE() AS ERRORSTATE,
			ERROR_PROCEDURE() AS ERRORPROCEDURE,
			ERROR_LINE() AS ERRORLINE,
			ERROR_MESSAGE() AS ERRORMESSAGE;

		ROLLBACK TRAN
	END CATCH

	SET NOCOUNT OFF;
END
GO

--ALTERAÇÃO NA VIEW [sis].[V_DADOS_FINANCEIRO]
ALTER VIEW [sis].[V_DADOS_FINANCEIRO]
AS
WITH DADOS_FINANCEIRO ( ID_FINANCEIRO, ID_FORMA_PAGAMENTO, FORMA_PAGAMENTO, ID_PESSOA, MES, ANO, REFER, DT_VENCIMENTO, VL_REFER, DIAS_VENCIDOS, FIN_JUROS_DIA, VL_DESCONTO, VL_DESCONTO_ALTERADO, DT_PAGAMENTO, VL_PAGO )
AS (
		SELECT
			ID_FINANCEIRO,
			F.ID_FORMA_PAGAMENTO,
			FP.DESCRICAO AS FORMA_PAGAMENTO,
			ID_PESSOA, 
			MES, 
			ANO,
			REFER,
			DT_VENCIMENTO,
			VL_REFER,

			CASE
				WHEN DATEDIFF(DAY, DT_VENCIMENTO, GETDATE()) > 0 THEN DATEDIFF(DAY, DT_VENCIMENTO, GETDATE())
			ELSE 0 END AS DIAS_VENCIDOS,

			CASE
				WHEN ( SELECT FIN_JUROS_DIA FROM [CFG].[CONFIGURACAO] WHERE FIN_ANO_CONTABIL = SUBSTRING(F.REFER, 3, 4) ) > 0 THEN ( SELECT FIN_JUROS_DIA FROM [CFG].[CONFIGURACAO] WHERE FIN_ANO_CONTABIL = SUBSTRING(F.REFER, 3, 4) )
			ELSE 0 END FIN_JUROS_DIA,

			CASE   
				WHEN VL_DESCONTO > 0 THEN VL_DESCONTO
				WHEN DATEDIFF(DAY, DT_VENCIMENTO, GETDATE()) <= 0 THEN VL_DESCONTO
			ELSE 0 END AS VL_DESCONTO,

			(SELECT TOP 1 VL_DESCONTO FROM [SIS].[FINANCEIRO_ALTERACAO] WHERE ID_FINANCEIRO = F.ID_FINANCEIRO ORDER BY DATA_OPERACAO DESC) AS VL_DESCONTO_ALTERADO,

			DT_PAGAMENTO,

			VL_PAGO

		FROM [sis].[FINANCEIRO] F

		LEFT JOIN [sis].[FORMA_PAGAMENTO] FP
			ON ( F.ID_FORMA_PAGAMENTO = FP.ID_FORMA_PAGAMENTO )
)
SELECT

	ID_FINANCEIRO,

	ID_FORMA_PAGAMENTO,

	FORMA_PAGAMENTO,

	ID_PESSOA,   
	
	MES, 
	
	ANO,

	REFER,

	DT_VENCIMENTO,

	VL_REFER,

	CASE		
		WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) > 0 THEN VL_DESCONTO_ALTERADO
		WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) <= 0 THEN 0
	ELSE
		CASE 
			WHEN VL_PAGO IS NULL THEN VL_DESCONTO
			WHEN ( VL_REFER - VL_PAGO ) > 0 THEN ( VL_REFER - VL_PAGO )
		ELSE 0
		END
	END AS VL_DESCONTO,

	CASE
		WHEN VL_PAGO IS NULL THEN ( COALESCE( DIAS_VENCIDOS, 0 ) * COALESCE( FIN_JUROS_DIA, 0 ) )
		WHEN ( VL_PAGO - VL_REFER ) > 0 THEN ( VL_PAGO - VL_REFER )
	ELSE 0
	END AS VL_JUROS,

	VL_REFER
	-
	CASE
		WHEN VL_PAGO IS NULL THEN CASE		
								     WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) > 0 THEN VL_DESCONTO_ALTERADO
									 WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) <= 0 THEN 0
								  ELSE
								     CASE 
									    WHEN VL_PAGO IS NULL THEN VL_DESCONTO
										WHEN ( VL_REFER - VL_PAGO ) > 0 THEN ( VL_REFER - VL_PAGO )
									 ELSE 0
									 END
								  END
		WHEN ( VL_REFER - VL_PAGO ) > 0 THEN ( VL_REFER - VL_PAGO )
		ELSE 0
	END
	+
	CASE
		WHEN VL_PAGO IS NULL THEN ( COALESCE( DIAS_VENCIDOS, 0 ) * COALESCE( FIN_JUROS_DIA, 0 ) )
		WHEN ( VL_PAGO - VL_REFER ) > 0 THEN ( VL_PAGO - VL_REFER )
	ELSE 0
	END AS VL_PAGAR,

	DT_PAGAMENTO,

	CASE
		WHEN VL_PAGO IS NOT NULL THEN VL_PAGO
		WHEN VL_PAGO IS NULL THEN CASE 
								     WHEN DT_PAGAMENTO IS NOT NULL THEN VL_REFER
																		-
																		CASE
																			WHEN VL_PAGO IS NULL THEN CASE		
																											WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) > 0 THEN VL_DESCONTO_ALTERADO
																											WHEN COALESCE( VL_DESCONTO_ALTERADO, 0) <= 0 THEN 0
																										ELSE
																											CASE 
																											WHEN VL_PAGO IS NULL THEN VL_DESCONTO
																											WHEN ( VL_REFER - VL_PAGO ) > 0 THEN ( VL_REFER - VL_PAGO )
																											ELSE 0
																											END
																										END
																			WHEN ( VL_REFER - VL_PAGO ) > 0 THEN ( VL_REFER - VL_PAGO )
																			ELSE 0
																		END
																		+
																		CASE
																			WHEN VL_PAGO IS NULL THEN ( COALESCE( DIAS_VENCIDOS, 0 ) * COALESCE( FIN_JUROS_DIA, 0 ) )
																			WHEN ( VL_PAGO - VL_REFER ) > 0 THEN ( VL_PAGO - VL_REFER )
																		ELSE 0
																		END
								     ELSE NULL
								  END
	END AS VL_PAGO

FROM DADOS_FINANCEIRO A
GO